export enum MEASUREMENT_UNITS {
  OZ = "oz",
  CUPS = "cups",
  GRAMS = "grams",
  LITERS = "liters",
  COUNT = "count",
  TABLESPOONS = "tbs",
  TEASPOONS = "tsp",
  MILLILITERS = "ml",
}

export const VOLUME_UNITS = [
  MEASUREMENT_UNITS.CUPS,
  MEASUREMENT_UNITS.LITERS,
  MEASUREMENT_UNITS.TABLESPOONS,
  MEASUREMENT_UNITS.TEASPOONS,
  MEASUREMENT_UNITS.MILLILITERS,
];

export const MASS_UNITS = [MEASUREMENT_UNITS.OZ, MEASUREMENT_UNITS.GRAMS];

export const UNIT_CONVERSIONS: {
  [key in MEASUREMENT_UNITS]?: { [key in MEASUREMENT_UNITS]?: number };
} = {
  [MEASUREMENT_UNITS.OZ]: {
    [MEASUREMENT_UNITS.GRAMS]: 28.3495,
    [MEASUREMENT_UNITS.TABLESPOONS]: 2,
    [MEASUREMENT_UNITS.TEASPOONS]: 6,
  },
  [MEASUREMENT_UNITS.GRAMS]: {
    [MEASUREMENT_UNITS.OZ]: 1 / 28.3495,
  },
  [MEASUREMENT_UNITS.TABLESPOONS]: {
    [MEASUREMENT_UNITS.TEASPOONS]: 3,
    [MEASUREMENT_UNITS.OZ]: 0.5,
  },
  [MEASUREMENT_UNITS.TEASPOONS]: {
    [MEASUREMENT_UNITS.TABLESPOONS]: 1 / 3,
    [MEASUREMENT_UNITS.OZ]: 1 / 6,
  },
  [MEASUREMENT_UNITS.LITERS]: {
    [MEASUREMENT_UNITS.MILLILITERS]: 1000,
  },
  [MEASUREMENT_UNITS.MILLILITERS]: {
    [MEASUREMENT_UNITS.LITERS]: 1 / 1000,
  },
  // Note: COUNT is intentionally not included in conversions
};
